name: Auto update dotfiles nvim submodule

on:
  push:
    branches: [main]

jobs:
  update_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout parent directory
        uses: actions/checkout@v4
        with:
          repository: Maxxxxxx-x/dotfiles
          token: ${{ secrets.DOTFILES_REPO_TOKEN }}
          submodules: true
          ref: master
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "gh-actions[bot]"
          git config user.email "gh-actions[bot]@users.noreply.github.com"

      - name: Update submodule
        id: update
        run: |
          git submodule update --init --remote --force worker

          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes needed"
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            git add worker
            LEFTHOOK=0 git commit --no-verify -m "chore: bumped worker submodule to ${{ github.sha }}"
          fi

      - name: Push changes
        if: steps.update.outputs.changed == 'true'
        run: git push origin main
